import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";
import TextSnippetIcon from '@mui/icons-material/TextSnippet';
import GlobalContextProvider from "@/ContextApi";

const inter = Inter({ subsets: ["latin"] });

const poppins  = Poppins({
  subsets:['latin'],
  variable:'--font-poppins',
  weight:['100','200','300','400','500','600','700','800','900']

})

export const metadata: Metadata = {
  title: "CodeSnip: Snipping Away Complexity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider publishableKey="pk_test_bHVja3ktdGVhbC0xMC5jbGVyay5hY2NvdW50cy5kZXYk" appearance={{
        baseTheme:neobrutalism,
        signIn:{baseTheme:neobrutalism},
      }}
      >
        <GlobalContextProvider>
      <body className={poppins.className}>{children}</body>
        </GlobalContextProvider>
      </ClerkProvider>
      
    </html>
  );
}
